/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class team_educoin_transaction_util_VerifyUtil */

#ifndef _Included_team_educoin_transaction_util_VerifyUtil
#define _Included_team_educoin_transaction_util_VerifyUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     team_educoin_transaction_util_VerifyUtil
 * Method:    verifyFingerprint
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_team_educoin_transaction_util_VerifyUtil_verifyFingerprint
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
